import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3001),
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('', null),
  JWT_ACCESS_TOKEN_SECRET: Joi.string().min(16).required(),
  JWT_ACCESS_TOKEN_EXPIRES_IN: Joi.string().default('900s'),
  JWT_REFRESH_TOKEN_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_TOKEN_EXPIRES_IN: Joi.string().default('7d'),
  ERP_SIMULATION_FAILURE_RATE: Joi.number().min(0).max(1).default(0.3),
  ERP_SIMULATION_MIN_DELAY_MS: Joi.number().min(0).default(800),
  ERP_SIMULATION_MAX_DELAY_MS: Joi.number().min(0).default(2500),
  IDEMPOTENCY_TTL_SECONDS: Joi.number().min(1).default(600),
  RATE_LIMIT_TTL: Joi.number().min(1).default(60),
  RATE_LIMIT_MAX: Joi.number().min(1).default(30),
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: Joi.number().min(1).default(5),
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: Joi.number().min(1000).default(60000),
  PRODUCTS_CACHE_TTL_SECONDS: Joi.number().min(5).default(60),
  CORS_ALLOWED_ORIGINS: Joi.string().default('http://localhost:3000'),
  CORS_ALLOWED_HEADERS: Joi.string().default(
    'Accept,Accept-Language,Content-Language,Authorization,Content-Type,Idempotency-Key,Request-Id',
  ),
  CORS_EXPOSED_HEADERS: Joi.string().default(
    'Request-Id,Retry-After,X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Reset',
  ),
  CORS_ALLOWED_METHODS: Joi.string().default('GET,POST,PUT,PATCH,DELETE,OPTIONS'),
  CORS_ALLOW_CREDENTIALS: Joi.boolean().truthy('true').falsy('false').default(true),
  CORS_MAX_AGE: Joi.number().min(0).default(600),
  SECURITY_HSTS_MAX_AGE: Joi.number().min(0).default(15552000),
  SECURITY_HSTS_INCLUDE_SUBDOMAINS: Joi.boolean().truthy('true').falsy('false').default(true),
  SECURITY_HSTS_PRELOAD: Joi.boolean().truthy('true').falsy('false').default(false),
  SECURITY_REFERRER_POLICY: Joi.string().default('no-referrer'),
  ADMIN_EMAIL: Joi.string().email().required(),
  ADMIN_PASSWORD: Joi.string().min(6).required(),
  CUSTOMER_EMAIL: Joi.string().email().required(),
  CUSTOMER_PASSWORD: Joi.string().min(6).required(),
});
